version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_database_final
    environment:
      MYSQL_ROOT_PASSWORD: final
      MYSQL_DATABASE: clinica
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
