version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_database_final
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./pkg/store/init.sql:/docker-entrypoint-initdb.d/init.sql

